Repository aau-giraf/wiki, pull requests merged in 2020-05, with the labels that each got.

#212 Feature 188
  docs/development/rest_api_development/EndpointsAndControllers.md
  docs/development/rest_api_development/EndpointsAndControllersTutorial.md
Labels: Gruppe 15

#219 Adding the approaches to implement the offline repository
  docs/development/Offline_mode.md
Labels: Gruppe 8

#238 Fixed hyperlinks
  docs/development/Offline_mode.md
Labels: Gruppe 8

#239 Releasefix 237
  docs/development/rest_api_development/EndpointsAndControllersTutorial.md
Labels: releaseFix

#243 Releasefix 231
  docs/development/Offline_mode.md
Labels: Gruppe 8
